name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4
      - name: Build cross container
        uses: docker/build-push-action@v7
        with:
          tags: "libretro-loongarch-cross"
          load: true
          cache-from: "type=gha,scope=libretro-loongarch-cross"
          cache-to: "type=gha,mode=max,scope=libretro-loongarch-cross"
      - name: Export environmental variables for sccache
        uses: actions/github-script@v9
        with:
          script: |
            core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
            core.exportVariable('ACTIONS_CACHE_SERVICE_V2', process.env.ACTIONS_CACHE_SERVICE_V2 || 'on');

      - name: Install package for crc32
        run: sudo apt-get update && sudo apt-get install -y libarchive-zip-perl

      - name: Install vcs2l
        run: pip3 install vcs2l

      - name: Restore repos
        run: vcs import --shallow libretro-super < lock.repos

      - name: Build cores
        run: scripts/build-all-ci.sh
        env:
          SCCACHE_GHA_ENABLED: "true"

      - name: Prepare site
        run: scripts/prepare-site.sh

      - uses: actions/upload-pages-artifact@v5
        with:
          include-hidden-files: true

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
